### PR TITLE
Updated README file in storage plugin example.

### LINKED ISSUE #570: Update README in storage plugin example
Update the README file in the storage plugin example: https://github.com/SINTEF/dlite/tree/master/examples/storage_plugin

The DLiteStorageBase now has more methods.

### PR DESCRIPTION
**Pull request by jesper-friis**
Description
 ===========
Closes #570

Type of change
--------------
- [ ] Bug fix
- [ ] New feature
- [x] Documentation update
- [ ] Test update

Checklist for the reviewer
--------------------------
This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

### CODE REVIEW

**Review by kriwiik — CHANGES_REQUESTED** [review]
Generally looks good, but please go over the example for testing the storage plugin and make sure it actually shows what is done in main.py. When I tried to just copy paste the example given in the readme I got path issues, and realized that the line for getting the instance is a bit different in main.py.

On line 11 in main.py we have: 
inst = dlite.Instance.from_location("tempprofile", "dataset.txt", "mode=r")

**Comment by jesper-friis** [comment]
> Generally looks good, but please go over the example for testing the storage plugin and make sure it actually shows what is done in main.py. When I tried to just copy paste the example given in the readme I got path issues, and realized that the line for getting the instance is a bit different in main.py.
> 
> On line 11 in main.py we have: inst = dlite.Instance.from_location("tempprofile", "dataset.txt", "mode=r")

Added a footnote to the README file clarifying the difference with `main.py`.

**Comment by kriwiik** [comment]
> 

Why not just change the example so it matches what can be found in main.py? When we are writing 

"We are now ready to test the storage plugin. A simple test is included in the [main.py](https://github.com/SINTEF/dlite/tree/master/examples/storage_plugin/main.py) script.

This script first appends the plugins/ sub-directory to the dlite.python_storage_plugin_path such that dlite is able to find the new plugin:"

it sounds like we will be going through the script.

Also, isn't it better to keep the code as it is in main.py so that the example we show here definitely works for everyone? What is the drawback? If I remove thisdir then the script fails and I have to figure out how to specify the path correctly in order for dlite to find the text file. Most users will probably figure it out, but why struggle when you don't have to? The footnote is now calling it good practice, so maybe we can just do it?

**Comment by jesper-friis** [comment]
> > 
> 
> Why not just change the example so it matches what can be found in main.py? When we are writing
> 
> "We are now ready to test the storage plugin. A simple test is included in the [main.py](https://github.com/SINTEF/dlite/tree/master/examples/storage_plugin/main.py) script.
> 
> This script first appends the plugins/ sub-directory to the dlite.python_storage_plugin_path such that dlite is able to find the new plugin:"
> 
> it sounds like we will be going through the script.
> 
> Also, isn't it better to keep the code as it is in main.py so that the example we show here definitely works for everyone? What is the drawback? If I remove thisdir then the script fails and I have to figure out how to specify the path correctly in order for dlite to find the text file. Most users will probably figure it out, but why struggle when you don't have to? The footnote is now calling it good practice, so maybe we can just do it?

You are completely right. I updated the readme to match main.py.

**Review by kriwiik — APPROVED** [review]

**Pull request merged**
