### PR TITLE
Initialise environment from global Python variables

### PR DESCRIPTION
**Pull request by jesper-friis**
# Description
Alternative to PR #988 for fixing issue #978.

This PR allows Python application to configure `dlite` via global variables.

Global variables in (the `__main__` module of) Python that starts with "DLITE_" will be set as environment variables seen by `dlite`. 

Hence, starting your application as

    DLITE_BEHAVIOR=ON python ./app.py

has the same effect as setting `DLITE_BEHAVIOR="ON"` before importing `dlite` in `app.py`.
 
## Type of change
- [ ] Bug fix & code cleanup
- [x] New feature
- [ ] Documentation update
- [ ] Test update

## Checklist for the reviewer
This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

### CODE REVIEW

**Comment by francescalb** [comment]
So do I understand correctly that with this change the warnings on bhaviour changes is remvoed by default when using dlite-validate? Can it be added if the users wants to? It would be good to write two sentences about this in the tools documentation (on dlite-validate)

**Comment by jesper-friis** [comment]
> So do I understand correctly that with this change the warnings on bhaviour changes is remvoed by default when using dlite-validate? Can it be added if the users wants to? It would be good to write two sentences about this in the tools documentation (on dlite-validate)

Yes, the behavior warning is now removed in dlite-validate. It is possible to add a separate or extend the --debug option to turn on behavior warnings. In that case we have to process the options before importing dlite. Would you prefer that?

**Comment by francescalb** [comment]
> > So do I understand correctly that with this change the warnings on bhaviour changes is remvoed by default when using dlite-validate? Can it be added if the users wants to? It would be good to write two sentences about this in the tools documentation (on dlite-validate)
> 
> Yes, the behavior warning is now removed in dlite-validate. It is possible to add a separate or extend the --debug option to turn on behavior warnings. In that case we have to process the options before importing dlite. Would you prefer that?

I am not sure we need it. but if it easy do add witht he debug option it might be a good idea.

**Comment by jesper-friis** [comment]
> > > So do I understand correctly that with this change the warnings on bhaviour changes is remvoed by default when using dlite-validate? Can it be added if the users wants to? It would be good to write two sentences about this in the tools documentation (on dlite-validate)
> > 
> > 
> > Yes, the behavior warning is now removed in dlite-validate. It is possible to add a separate or extend the --debug option to turn on behavior warnings. In that case we have to process the options before importing dlite. Would you prefer that?
> 
> I am not sure we need it. but if it easy do add witht he debug option it might be a good idea.

Done. Also made sure that needed cmake configurations are available in dlite-pyembed.c

**Review by francescalb — APPROVED** [review]

**Pull request merged**
